const types = {
    GET_ALL_POKEMONS_START: 'GET_ALL_POKEMONS_START',
    GET_ALL_POKEMONS_FULFILLED: 'GET_ALL_POKEMONS_FULFILLED',
    GET_ALL_POKEMONS_FAILED: 'GET_ALL_POKEMONS_FAILED',
    GET_ALL_POKEMONS: 'GET_ALL_POKEMONS',
}

export default types;